name: Release

on: [push]

jobs:
  build:
    name: build&test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.16.x]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm ci
        run: npm ci
        


      - name: Axios
        run: npm install axios 

      - name: post Release Message
        run: npm run postReleaseMessage
        env: 
           GITHUB_TOKEN: ${{ secrets.GITHUBAPI_TOKEN }} 
           release_name: Release ${{ github.ref }}
           yandex_auth_token: ${{ secrets.secrets.YANDEX_AUTH_TOKEN }} 
           app_id: ${{ secrets.APP_ID }} 
           

      - name: Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBAPI_TOKEN }} 
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      
