name: Release

on:
  push:
    tags:        
      - 'rc-*'

jobs:
  build:
    name: build&test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.16.x]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm ci
        run: npm ci
        
      - name: npm run build
        run: npm run build

      - name: npm run test
        run: npm run test

      - name: Commit actor
        run: echo "${{ GITHUB.ACTOR }}"  

      - name: ref
        run: echo "${{ github.ref  }}"

      - name: post Release Message
        run: npm postReleasMessage

      - name: Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBAPI_TOKEN }} 
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      
